/*
 *
 * --help.c
 * This file is automatically generated; please do not edit it.
 */
	{0, 0}
};

static const struct PRErrorTable et = { text, "--help", 0L, 0 };

void _InitializePRErrorTable(void) {
    PR_ErrorInstallTable(&et);
}
