BUILTIN_ARGS = {
    "trivy": [
        ("image nginx:latest", "Scan image"),
        ("fs /", "Filesystem scan"),
        ("--severity CRITICAL,HIGH image nginx:latest", "Critical only"),
    ],
    "kube-hunter": [
        ("--remote target.com", "Remote scan"),
        ("--active", "Active hunting"),
        ("--pod", "Inside pod"),
    ],
    "docker": [
        ("ps -a", "List containers"),
        ("images", "List images"),
        ("run -it ubuntu bash", "Run interactive"),
        ("exec -it container bash", "Exec into container"),
    ],
    "kubectl": [
        ("get pods", "List pods"),
        ("get pods --all-namespaces", "All namespaces"),
        ("exec -it pod -- bash", "Exec into pod"),
        ("apply -f deployment.yaml", "Apply config"),
    ],
    "terraform": [
        ("init", "Initialize"),
        ("plan", "Plan changes"),
        ("apply -auto-approve", "Apply changes"),
    ],
    "lynis": [
        ("audit system", "System audit"),
        ("audit system --quick", "Quick scan"),
        ("audit system --pentest", "Pentest mode"),
    ],
    "chkrootkit": [("-q", "Quiet mode")],
    "rkhunter": [("--check", "Full check"), ("--update", "Update database")],
    "clamscan": [("-r /", "Scan root"), ("-r --bell /home", "Alert on find")],
    "testdisk": [("/dev/sda", "Analyze disk")],
    "photorec": [("/dev/sda", "Recover from disk")],
    "foremost": [("-i image.dd -o output/", "Carve files")],
    "volatility3": [
        ("-f memory.dump windows.info", "System info"),
        ("-f memory.dump windows.pslist", "Process list"),
        ("-f memory.dump windows.netscan", "Network scan"),
    ],
    "apktool": [("d app.apk", "Decompile"), ("b app/ -o new.apk", "Build")],
    "jadx": [("app.apk", "Decompile"), ("-d output/ app.apk", "Output directory")],
    "ghidra": [("-import binary.exe -postscript AnalyzeHeadless", "Import analyze")],
    "radare2": [("-A binary", "Auto analyze"), ("-d binary", "Debug mode")],
    "objdump": [("-d binary", "Disassemble"), ("-x binary", "All headers")],
    "strace": [("-f command", "Follow forks"), ("-c command", "Summary count")],
    "gdb": [("-q binary", "Quiet start"), ("-p PID", "Attach to process")],
    "ssh": [
        ("user@host", "Basic connect"),
        ("-p 2222 user@host", "Custom port"),
        ("-i key.pem user@host", "Key auth"),
        ("-L 8080:localhost:80 user@host", "Local forward"),
        ("-D 1080 user@host", "SOCKS proxy"),
    ],
    "openssl": [
        ("genrsa -out key.pem 2048", "Generate RSA key"),
        ("req -new -key key.pem -out csr.pem", "Generate CSR"),
        ("s_client -connect target.com:443", "SSL connect"),
    ],
    "gpg": [
        ("-c file.txt", "Symmetric encrypt"),
        ("-d file.gpg", "Decrypt"),
        ("--list-keys", "List keys"),
    ],
    "git": [
        ("clone https://github.com/user/repo.git", "Clone repo"),
        ("clone --depth 1 https://github.com/user/repo.git", "Shallow clone"),
    ],
    "python3": [("-m http.server 8080", "HTTP server"), ("-c print(1)", "One-liner")],
    "pip": [("install package", "Install"), ("list", "List installed")],
    "wget": [("https://target.com/file.txt", "Download"), ("-r -np -k https://target.com", "Mirror site")],
    "tar": [("-czf archive.tar.gz dir/", "Create gzip"), ("-xzf archive.tar.gz", "Extract")],
    "zip": [("archive.zip file1 file2", "Create archive"), ("-P password archive.zip file", "With password")],
    "dd": [("if=/dev/sda of=image.dd bs=4M status=progress", "Disk image")],
    "shred": [("-n 7 -z file.txt", "7 pass shred"), ("-u file.txt", "Remove after")],
    "iptables": [("-L -n -v", "List rules"), ("-A INPUT -s IP -j DROP", "Block IP")],
    "netstat": [("-tunap", "All connections"), ("-tlnp", "Listening ports")],
    "arp": [("-a", "ARP table")],
    "screen": [("-S name", "Named session"), ("-r name", "Reattach")],
    "tmux": [("new -s name", "New session"), ("attach -t name", "Attach")],
}
