BUILTIN_ARGS = {
    "nmap": [
        ("-F target.com", "Fast scan top 100 ports"),
        ("-sV target.com", "Service version detection"),
        ("-sC target.com", "Default scripts"),
        ("-sV -sC -O target.com", "Full audit"),
        ("-p- target.com", "All 65535 ports"),
        ("-p 1-1000 target.com", "Top 1000 ports"),
        ("-sS -T4 target.com", "Stealth SYN scan"),
        ("-sU target.com", "UDP scan"),
        ("--script vuln target.com", "Vulnerability scan"),
        ("--script brute target.com", "Brute force scripts"),
        ("--script exploit target.com", "Exploit detection"),
        ("-A -T4 target.com", "Aggressive scan"),
        ("-sn 192.168.1.0/24", "Ping sweep network"),
    ],
    "gobuster": [
        ("dir -u http://target.com -w wordlist.txt", "Directory brute"),
        ("dns -d target.com -w wordlist.txt", "DNS subdomain brute"),
        ("vhost -u http://target.com -w wordlist.txt", "Virtual host brute"),
        ("dir -u http://target.com -w wordlist.txt -x php,html,txt", "With extensions"),
        ("dir -u http://target.com -w wordlist.txt -t 100", "100 threads"),
        ("dir -u http://target.com -w wordlist.txt -k", "Skip SSL verify"),
    ],
    "hydra": [
        ("-l admin -P rockyou.txt ssh://target", "SSH single user brute"),
        ("-L users.txt -P pass.txt ssh://target", "SSH user list brute"),
        ("-l admin -P pass.txt ftp://target", "FTP brute"),
        ("-l root -P pass.txt mysql://target", "MySQL brute"),
        ("-L users.txt -P pass.txt http-post-form://target/login:user=USER&pass=PASS:F=error", "HTTP form brute"),
        ("-L users.txt -P pass.txt smb://target", "SMB brute"),
        ("-l admin -P pass.txt rdp://target", "RDP brute"),
        ("-t 16 -f -V -l admin -P pass.txt ssh://target", "Fast single user brute"),
    ],
    "sqlmap": [
        ("-u http://target.com/page.php?id=1", "Basic test"),
        ("-u http://target.com/page.php?id=1 --dbs", "Enumerate databases"),
        ("-u http://target.com/page.php?id=1 -D db --tables", "Enumerate tables"),
        ("-u http://target.com/page.php?id=1 -D db -T users --dump", "Dump table"),
        ("-u http://target.com/page.php?id=1 --batch", "Auto answers"),
        ("-u http://target.com/page.php?id=1 --level=5 --risk=3", "Max level risk"),
        ("-u http://target.com/page.php?id=1 --os-shell", "OS shell attempt"),
        ("-u http://target.com/page.php?id=1 --tamper=space2comment", "WAF bypass"),
    ],
    "john": [
        ("--wordlist=rockyou.txt hash.txt", "Dictionary attack"),
        ("--rules --wordlist=rockyou.txt hash.txt", "Rules attack"),
        ("--incremental hash.txt", "Incremental brute"),
        ("--format=raw-md5 hash.txt", "MD5 format"),
        ("--format=raw-sha256 hash.txt", "SHA256 format"),
        ("--show hash.txt", "Show cracked"),
    ],
    "hashcat": [
        ("-m 0 -a 0 hash.txt rockyou.txt", "MD5 dictionary"),
        ("-m 0 -a 3 hash.txt ?l?l?l?l?l?l", "MD5 mask brute 6 lower"),
        ("-m 1000 -a 0 hash.txt rockyou.txt", "NTLM dictionary"),
        ("-m 2500 -a 0 hash.hc22000 rockyou.txt", "WPA dictionary"),
        ("-m 0 -a 0 hash.txt rockyou.txt -O -w 4", "Optimized max power"),
        ("-m 0 -a 3 hash.txt ?a?a?a?a?a?a?a?a", "8 char all charset brute"),
    ],
}
